# Generated by Django 4.1.2 on 2022-10-18 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_postbody_post'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postbody',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='body_list', to='blog.post'),
        ),
    ]
